Repository dooboolab/hackatalk-server, pull requests merged in 2020-02, with the labels that each got.

#29 Add photos table associate to [Message]
  schemas/message.graphql
  schemas/photo.graphql
  schemas/schema.graphql
  src/generated/graphql.ts
  src/models/Photo.ts
  src/models/index.ts
  src/server.ts
Labels: migration, models

#32 Implement single storage upload rest api
  dotenv/dev.env
  dotenv/test.env
  package.json
  src/app.ts
  src/server.ts
  src/utils/auth.ts
  src/utils/azure.ts
  yarn.lock
Labels: feature

#31 Add channel resolver
  .circleci/config.yml
  jest.config.js
  package.json
  schemas/channel.graphql
  src/context.ts
  src/generated/graphql.ts
  src/models/Friend.ts
  src/models/Membership.ts
  src/resolvers/channel.ts
  src/resolvers/user.ts
  src/server.ts
  src/utils/auth.ts
  tests/channel.test.ts
  tests/testSetup.ts
  tests/user.test.ts
Labels: feature

#34 Add email verification mutation
  config/config.js
  schemas/schema.graphql
  src/app.ts
  src/generated/graphql.ts
  src/models/User.ts
  src/resolvers/user.ts
  src/utils/auth.ts
  tests/testSetup.ts
  tests/user.test.ts
Labels: feature

#36 Add contributing badge
  README.md
Labels: documentation

#39 Implement resolvers for new model [Gallery]
  codegen.yml
  package.json
  schemas/gallery.graphql
  schemas/schema.graphql
  src/generated/graphql.ts
  src/models/Gallery.ts
  src/models/index.ts
  src/resolvers/gallery.ts
  src/resolvers/index.ts
  src/resolvers/user.ts
  src/server.ts
  src/utils/auth.ts
  src/utils/azure.ts
  yarn.lock
Labels: feature

#41 Include changeEmailPassword mutation query
  schemas/schema.graphql
  src/generated/graphql.ts
  src/resolvers/user.ts
Labels: feature

#44 Support pagination and like statement
  schemas/schema.graphql
  src/generated/graphql.ts
  src/resolvers/user.ts
Labels: feature

#45 Enhancement and fixes for #44
  schemas/schema.graphql
  src/generated/graphql.ts
  src/resolvers/user.ts
Labels: hotfix

#50 Add tests to gallery
  .circleci/config.yml
  package.json
  src/resolvers/gallery.ts
  src/utils/auth.ts
  tests/gallery.test.ts
Labels: enhancement, testings

#53 Support localization
  locales/en.json
  locales/ko.json
  package.json
  src/app.ts
  yarn.lock
Labels: feature

#56 Migration for shortening tests and handling error strings
  src/app.ts
  src/db/index.ts
  src/resolvers/channel.ts
  src/resolvers/friend.ts
  src/resolvers/gallery.ts
  src/resolvers/message.ts
  src/resolvers/notification.ts
  src/resolvers/user.ts
  src/utils/auth.ts
  src/utils/error.ts
  tests/channel.test.ts
  tests/gallery.test.ts
Labels: enhancement, refactor

#46 Add Query virgilJwt to User Resolver
  .circleci/config.yml
  dotenv/dev.env
  dotenv/test.env
  package.json
  schemas/schema.graphql
  src/generated/graphql.ts
  src/resolvers/user.ts
  src/utils/virgil.ts
  yarn.lock
Labels: feature

#49 Replace 'sequelize.sync()' with 'yarn migrate'
  .gitignore
  migrations/20200215063339-Channel.js
  migrations/20200215073023-User.js
  migrations/20200215075119-Membership.js
  migrations/20200215080655-Friend.js
  migrations/20200215080929-Gallery.js
  migrations/20200215081121-Message.js
  migrations/20200215081307-Notification.js
  migrations/20200215081505-Photo.js
  migrations/20200215081658-Reply.js
  migrations/20200216091406-Message.js
  package.json
  src/db/index.ts
  src/models/Message.ts
  src/utils/auth.ts
Labels: enhancement

#58 [enhancement][user] modify "updateProfile" resolver add "thumbURL", "photoURL" in UserProfileInput
  migrations/20200222135717-User.js
  schemas/user.graphql
  src/models/User.ts
  src/resolvers/user.ts
  tests/user.test.ts
Labels: bugfix, enhancement

#60 Send virgil token to user field when sign in
  __mocks__/virgil-crypto.ts
  __mocks__/virgil-sdk.ts
  dotenv/dev.env
  dotenv/test.env
  schemas/user.graphql
  src/generated/graphql.ts
  src/resolvers/user.ts
  tests/user.test.ts
Labels: enhancement

#61 Remove virgilToken resolver and provider rest api
  schemas/schema.graphql
  schemas/user.graphql
  src/app.ts
  src/generated/graphql.ts
  src/resolvers/user.ts
Labels: feature, migration
