Repository dooboolab/hackatalk-server, pull requests merged in 2020-03, with the labels that each got.

#63 Initial proposal for createMesage resolver
  schemas/message.graphql
  schemas/schema.graphql
  src/generated/graphql.ts
  src/models/Channel.ts
  src/models/Friend.ts
  src/models/Gallery.ts
  src/models/Membership.ts
  src/models/Message.ts
  src/models/Notification.ts
  src/models/Photo.ts
  src/models/Reply.ts
  src/models/User.ts
  src/resolvers/message.ts
  src/resolvers/user.ts
  src/utils/error.ts
  tests/message.test.ts
Labels: feature

#65 [Enhance] Remove duplicated SignUp Mutation in test files
  tests/channel.test.ts
  tests/gallery.test.ts
  tests/user.test.ts
Labels: enhancement, testings

#62 Implement Pagination: User
  schemas/pagination.graphql
  schemas/schema.graphql
  schemas/user.graphql
  src/generated/graphql.ts
  src/resolvers/user.ts
  src/utils/error.ts
  src/utils/pagination.ts
  tests/testSetup.ts
  tests/user.test.ts
Labels: enhancement, feature

#59 Add single upload resolver
  .gitignore
  package.json
  schemas/file.graphql
  schemas/schema.graphql
  src/generated/graphql.ts
  src/resolvers/file.ts
  src/resolvers/index.ts
  src/server.ts
  src/utils/azure.ts
  tests/file.test.ts
  yarn.lock
Labels: feature

#70 Refactor createChannel and createMessage
  schemas/schema.graphql
  src/generated/graphql.ts
  src/resolvers/channel.ts
  src/resolvers/message.ts
  src/utils/error.ts
  tests/channel.test.ts
  tests/message.test.ts
Labels: refactor

#71 Add 'message' test case of having message in channel's query after creating message
  tests/channel.test.ts
  tests/message.test.ts
Labels: testings

#73 Enhance update password resolver with testing
  src/resolvers/user.ts
  tests/user.test.ts
Labels: enhancement
