Repository dooboolab/hackatalk-server, pull requests merged in 2020-01, with the labels that each got.

#13 [Refactoring] Refactor and arrange codes, And add models.
  .circleci/config.yml
  .vscode/launch.json
  schemas/auth.graphql
  schemas/chat.graphql
  schemas/chatroom.graphql
  schemas/friend.graphql
  schemas/membership.graphql
  schemas/schema.graphql
  schemas/user.graphql
  src/app.ts
  src/generated/graphql.ts
  src/models/Auth.ts
  src/models/Chat.ts
  src/models/Chatroom.ts
  src/models/Friend.ts
  src/models/Membership.ts
  src/models/Notification.ts
  src/models/Review.ts
  src/models/Role.ts
  src/models/User.ts
  src/models/index.ts
  src/resolvers/chat.ts
  src/resolvers/chatroom.ts
  src/resolvers/friend.ts
  src/resolvers/notification.ts
  src/resolvers/user.ts
  src/server.ts
  src/types/index.ts
  src/utils/encryption.ts
  src/utils/password.ts
  tests/user.test.ts
Labels: feature, refactor

#18 Add typings and refactored codebase
  .eslintrc.js
  package.json
  schemas/channel.graphql
  schemas/membership.graphql
  schemas/message.graphql
  schemas/review.graphql
  schemas/schema.graphql
  schemas/user.graphql
  src/app.ts
  src/generated/graphql.ts
  src/models/Auth.ts
  src/models/Channel.ts
  src/models/Friend.ts
  src/models/Membership.ts
  src/models/Message.ts
  src/models/Notification.ts
  src/models/Review.ts
  src/models/Role.ts
  src/models/User.ts
  src/models/index.ts
  src/resolvers/channel.ts
  src/resolvers/chat.ts
  src/resolvers/chatroom.ts
  src/resolvers/friend.ts
  src/resolvers/index.ts
  src/resolvers/message.ts
  src/resolvers/notification.ts
  src/resolvers/review.ts
  src/resolvers/user.ts
  src/server.ts
  src/utils/password.ts
  tests/user.test.ts
  tsconfig.json
  yarn.lock
Labels: refactor

#19 Enhance typings for models and schema
  codegen.yml
  schemas/channel.graphql
  schemas/friend.graphql
  schemas/membership.graphql
  schemas/message.graphql
  schemas/notification.graphql
  schemas/schema.graphql
  schemas/user.graphql
  src/context.ts
  src/db/index.ts
  src/generated/graphql.ts
  src/models/Channel.ts
  src/models/Friend.ts
  src/models/Membership.ts
  src/models/Message.ts
  src/models/Notification.ts
  src/models/User.ts
  src/models/index.ts
  src/resolvers/channel.ts
  src/resolvers/friend.ts
  src/resolvers/notification.ts
  src/resolvers/user.ts
  src/server.ts
Labels: enhancement, typings

#22 More resolvers
  .vscode/settings.json
  package.json
  schemas/schema.graphql
  schemas/user.graphql
  src/generated/graphql.ts
  src/resolvers/friend.ts
  src/resolvers/message.ts
  src/resolvers/user.ts
  yarn.lock
Labels: feature

#25 Enhance resolvers with integration
  config/config.js
  migrations/20200126063808-User.js
  package.json
  schemas/schema.graphql
  schemas/user.graphql
  src/db/index.ts
  src/generated/graphql.ts
  src/models/User.ts
  src/resolvers/user.ts
Labels: enhancement

#27 Enhance resolvers and organize all graphql apis given
  migrations/20200127105045-Channel.js
  package.json
  schemas/channel.graphql
  schemas/friend.graphql
  schemas/notification.graphql
  schemas/schema.graphql
  schemas/user.graphql
  src/db/index.ts
  src/generated/graphql.ts
  src/models/Channel.ts
  src/resolvers/channel.ts
  src/resolvers/friend.ts
  src/resolvers/index.ts
  src/resolvers/notification.ts
  src/resolvers/user.ts
  src/server.ts
Labels: enhancement

#28 Add api to check on/offline status for user
  schemas/schema.graphql
  src/app.ts
  src/generated/graphql.ts
  src/resolvers/user.ts
Labels: feature
