Repository dooboolab/hackatalk-server, pull requests merged in 2020-05, with the labels that each got.

#79 Apply Facebook social login validation
  .circleci/config.yml
  .eslintrc.js
  package.json
  schemas/schema.graphql
  src/generated/graphql.ts
  src/resolvers/user.ts
Labels: enhancement

#83 Refine test codes and Fix bug of pagination logic
  src/resolvers/user.ts
  src/utils/pagination.ts
  tests/testSetup.ts
  tests/user.test.ts
  yarn.lock
Labels: bugfix

#82 Upgrade packages and circleci mysql=>8.0.4
  .circleci/config.yml
  .eslintrc.js
  README.md
  dotenv/dev.env
  jest.config.js
  package.json
  src/models/Channel.ts
  src/models/Friend.ts
  src/models/Gallery.ts
  src/models/Membership.ts
  src/models/Message.ts
  src/models/Notification.ts
  src/models/Photo.ts
  src/models/Reaction.ts
  src/models/Reply.ts
  src/models/User.ts
  src/models/index.ts
  src/resolvers/notification.ts
  yarn.lock
Labels: migration, upgrade packages

#84 Refactor Subscriptions
  schemas/schema.graphql
  src/generated/graphql.ts
  src/resolvers/friend.ts
  src/resolvers/user.ts
Labels: bugfix, refactor

#85 Change test db url for ci
  .circleci/config.yml
  dotenv/dev.env
  dotenv/test.env
  package.json
  src/models/Membership.ts
  tests/gallery.test.ts
  tests/reaction.test.ts
  yarn.lock
Labels: ci, config, testings
