Repository dooboolab/hackatalk-server, pull requests merged in 2020-06, with the labels that each got.

#90 Fix the 404 ERROR when hash value contain '/'(%2F)
  src/utils/auth.ts
Labels: bugfix

#92 Change auth enum types
  migrations/20200215073023-User.js
  package.json
  schemas/user.graphql
  src/generated/graphql.ts
  src/models/User.ts
Labels: enhancement

#93 Upgrade packages
  package.json
  yarn.lock
Labels: upgrade packages
